version: "2"

services:
  nginx:
    image: nginx:1.13.7
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx/log:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - wordpress:php
    depends_on:
      - "mariadb"
    networks:
      - "shared_network"

  wordpress:
    image: wordpress:4.9.1-fpm
    environment:
      WORDPRESS_DB_HOST: "mariadb"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_PASSWORD: ""
      WORDPRESS_TABLE_PREFIX: "wp_"
    volumes:
      - ./wordpress:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./php/log:/var/log/php
    links:
      - mariadb:mysql
    networks:
      - shared_network
    depends_on: 
      - mariadb

  mariadb:
    image: mariadb:10.2.11
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - "shared_network"

networks:
  shared_network: {}
